# MIT License
#
# Copyright (c) 2022-2022 Carlo Corradini
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

autoscaler:
  url: https://github.com/carlocorradini/autoscaler.git
  assets:
    - cluster-autoscaler.amd64.tar.gz
    - cluster-autoscaler.arm64.tar.gz
  releases:
    - latest

k3s:
  url: https://github.com/k3s-io/k3s.git
  assets:
    - k3s
    - k3s-airgap-images-amd64.tar.gz
  releases:
    - latest
  files:
    install.sh: https://raw.githubusercontent.com/k3s-io/k3s/master/install.sh

node_exporter:
  url: https://github.com/prometheus/node_exporter.git
  assets:
    - node_exporter-[0-9]+.[0-9]+.[0-9]+.linux-amd64.tar.gz
  releases:
    - latest
  files:
    install.sh: https://raw.githubusercontent.com/carlocorradini/node_exporter_installer/main/install.sh

prometheus:
  url: https://github.com/prometheus/prometheus.git
  assets:
    - prometheus-[0-9]+.[0-9]+.[0-9]+.linux-amd64.tar.gz
  releases:
    - latest
