# MIT License
#
# Copyright (c) 2022-2023 Carlo Corradini
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

__:
  run: |-
    ./scripts/inline.sh --in-file ./install.sh --overwrite
install.sh: true
LICENSE: true
README.md: true
configs:
  README.md: true
  certs: true
  k3s: true
  k8s:
    README.md: true
    autoscaler: true
    loadbalancer:
      __:
        run: |-
          wget --output-document=deployment.yaml https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/manifests/metallb-native.yaml
      config.yaml: true
      deployment.yaml: true
      README.md: true
    registry: true
  node_exporter: true
  recluster: true
  ssh: true
dependencies:
  __:
    run: |-
      ./dependencies/dependencies.sh --sync-force
  autoscaler: true
  k3s: true
  node_exporter: true
  prometheus: true
distributions:
  alpine:
    __:
      run: |-
        ./distributions/alpine/build.sh
    README.md: true
    logo.png: true
    iso: true
  arch: false
docs: true
scripts:
  __:
    run: |-
      ./scripts/inline.sh --in-file ./certs.sh --overwrite
      ./scripts/inline.sh --in-file ./configs.sh --overwrite
  README.md: true
  certs.sh: true
  configs.sh: true
  configs.config.yaml: true
server:
  __:
    run: |-
      npm run build:clean
      npm run build
  README.md: true
  package.json: true
  package-lock.json: true
  build: true
  prisma:
    schema.prisma: true
    migrations: true
