# MIT License
#
# Copyright (c) 2022-2022 Carlo Corradini
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

k3s:
  token: '4646f99bc4cbae3d5eceed856b337c9d3284be0d4056a3909f780c0c385fbf93'
  server:
    host: '192.168.0.100'
    port: 6443

k8s:
  loadbalancer:
    ip:
      from: '192.168.0.200'
      to: '192.168.0.250'
  registry:
    mirror:
      host: 'registry.recluster.local'
      port: 5000
    endpoint:
      host: '192.168.0.202'
      port: 5000
    tls:
      crt:
        __:
          run: |-
            base64 -w 0 ./certs/registry.crt
      key:
        __:
          run: |-
            base64 -w 0 ./certs/registry.key

recluster:
  server:
    host: '192.168.0.100'
    port: 8080
    path: 'graphql'
  database:
    user: 'recluster'
    password: 'password'
    host: 'localhost'
    port: 5432
    db: 'recluster'

ssh:
  authorized_key:
    __:
      run: |-
        cat ./certs/ssh.crt
